# 빌드 단계
FROM node:18-alpine AS build

WORKDIR /app

# 패키지 파일 복사 및 설치
COPY package*.json ./
RUN npm install

# 소스 코드 복사 전에 .env.production 복사
COPY .env.production .env.production

# 소스 코드 복사
COPY . .

# 프로덕션 빌드
RUN npm run build

# 실행 단계
FROM nginx:alpine

# Nginx 설정
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
